### ISSUE TITLE
Modded scripts doesn't work.

### ISSUE THREAD

**Issue by ParanoidDoll** [k0np4ku/Azur-Lane-Scripts-Autopatcher#12]
Modded scripts are generated and the game runs with it but it doesn't seem to do to anything. Used the damage+weak enemy mod but it stayed the same.

Game version is 1.4.22(JP)

**Comment by Sora92** [comment]
i got the same problem

**Comment by k0np4ku** [comment]
Read https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/issues/9#issuecomment-406273704

**Comment by ParanoidDoll** [comment]
It's working now, thanks! Just found out that I forgot to update the **Path**  in System Environment Variables when I installed my Python 3.7.0.
