### ISSUE TITLE
All types are forcibly created

### ISSUE THREAD

**Issue by nanika0000** [k0np4ku/Azur-Lane-Scripts-Autopatcher#13]
i edit Configuration.ini To exclude except Godmode_Damage_Cooldown_Weakenemy
but make 8 files.
It seems that Editing Configuration.ini does not actually become effective
Even if you edit it, it will be recreated by default

**Comment by nanika0000** [comment]
Since it is initialized, even debugging can not be enabled

**Comment by k0np4ku** [comment]
Please upload your Configuration.ini

**Comment by nanika0000** [comment]
[Configuration.zip](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2237813/Configuration.zip)

**Comment by k0np4ku** [comment]
https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/releases/tag/v2.8.2f

**Comment by k0np4ku** [comment]
Uhh, sorry? I don't understand, what do you mean?

**Comment by nanika0000** [comment]
[Debug.zip](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2237928/Debug.zip)
Here's what bad_Configuration.ini is enabled for debugging

**Comment by neoxfree** [comment]
sorry i have a problem, i created 7 file all didn't work in game i try all.

**Comment by k0np4ku** [comment]
@neoxfree what do you mean by `didn't work`? Does all the scripts have the same size? If yes, try read this https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/issues/9#issuecomment-406273704

**Comment by neoxfree** [comment]
yaya
