### ISSUE TITLE
Doesn't work in PVP?

### ISSUE THREAD

**Issue by Morisatos** [k0np4ku/Azur-Lane-Scripts-Autopatcher#15]
Any way you can make one for PVP k0np4ku? Seems the enemy auto ai in pvp also has script benefits as well which quickly wipes out your own team.

**Comment by k0np4ku** [comment]
Nope, it's on purpose that the scripts won't give you an advantage in PvP mode... otherwise the rankings would be ruined and the mod won't have a long lifespan. Just avoid the rankings, PvP is useless once your level is high enough.
