### ISSUE TITLE
AL Scripts Autopatcher v2.8.2-fix3  Patch does not work

### ISSUE THREAD

**Issue by syramashiroM** [k0np4ku/Azur-Lane-Scripts-Autopatcher#16]
First, thank you for the hard patch that you have worked hard to make.
AL EN version  8/30 Update  
I use AL Scripts Autopatcher v2.8.2-fix3 
But the patch that was made has no effect at all.
If you have time, I hope I can check it. 
（ps：My English is not good, I hope you can understand, understand what I mean.）

**Comment by k0np4ku** [comment]
Everything works fine on my end. 
Install the system requirements of this tool and change your system locale to English.

**Comment by syramashiroM** [comment]
I want to explain that there is no problem with the tool. 8.30EN VERSION before the update version. No problem with the patch. The scripts created after the update are completely ineffective.



My question is whether it is possible to replace the encryption method after the EN VERSION update. The patch has no effect after the creation.

**Comment by syramashiroM** [comment]
I need to install the patch system. I think the tools are ready to use.
