### ISSUE TITLE
I can't use the client.

### ISSUE THREAD

**Issue by lkq13905940077** [k0np4ku/Azur-Lane-Scripts-Autopatcher#19]
I can't use the client.I can't delete that paragraph by dnspy.Can you give me some picture tutorials?

**Comment by k0np4ku** [comment]
Here you go, this is a video, download and extract it.
[2018-09-02_07-25-49.zip](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2342877/2018-09-02_07-25-49.zip)

**Comment by lkq13905940077** [comment]
Thank you. The problem has been solved.Can you teach me how to change the name of SC, like changing the name of SC to my name?

**Comment by lkq13905940077** [comment]
Thank you. The problem has been solved.Can you teach me how to change the name of SC, like changing the name of SC to my name?

**Comment by k0np4ku** [comment]
I don't know what you're talking about, what is SC?

**Comment by lkq13905940077** [comment]
The name is not scripts, it can be other

**Comment by lkq13905940077** [comment]
The name is not scripts, it can be other

**Comment by k0np4ku** [comment]
Well you can if you figure it out by yourself, I won't explain it to you because it's pain in the ass.

**Comment by lkq13905940077** [comment]
I don't understand, I can't translate.

**Comment by k0np4ku** [comment]
Where did you get it from? I can't do much about it if I know nothing about it.

**Comment by lkq13905940077** [comment]
A free plug-in group

**Comment by k0np4ku** [comment]
The scripts has a different encryption algorithm and is impossible for normal apk to process the file. Do you have the modded apk?

**Comment by lkq13905940077** [comment]
yes，do you have qq？I give you

**Comment by k0np4ku** [comment]
I'm not chinese so I can't access qq, can you upload it somewhere like google drive or mega? or I'll give you my e-mail address if you somehow don't want it to be public.

**Comment by lkq13905940077** [comment]
There is another problem. The installation package is not installed.

**Comment by k0np4ku** [comment]
You must re-sign the apk

**Comment by lkq13905940077** [comment]
What shall I do?

**Comment by lkq13905940077** [comment]
Do you have a WeChat account? Or the QQ International Edition.

**Comment by k0np4ku** [comment]
Use this tool to sign the apk [Portable](https://evildog1.bitbucket.io/apkeasytool/APK%20Easy%20Tool%20portable.zip) or [Installer](https://evildog1.bitbucket.io/apkeasytool/APK%20Easy%20Tool%20Setup.msi)

**Comment by k0np4ku** [comment]
I don't have WeChat or QQ since both requires phone numbers, which I can't trust them due to privacy issues. Well I can't do much.

**Comment by lkq13905940077** [comment]
emmmm，Then how should I give it to you? I can't go to Google. There's a wall.

**Comment by lkq13905940077** [comment]
Then how should I give it to you? I can't go to Google.

**Comment by k0np4ku** [comment]
I can't do much about The Great Firewall of China. You can try upload it on mega.nz, dropbox or use vpn, even baidu is fine to me.

**Comment by lkq13905940077** [comment]
I'll give you a Baidu cloud later.

**Comment by lkq13905940077** [comment]
By the way, we can communicate through Baidu post bar. You can register with a mailbox. You can't sell it. Taobao also sells it.

**Comment by k0np4ku** [comment]
Are you sure that the link you just posted is valid? Because it says "此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！"

**Comment by lkq13905940077** [comment]
链接:https://pan.baidu.com/s/1_ZcB6hNG3hiqLT-pt_9vsQ 密码:1417

**Comment by lkq13905940077** [comment]
cry it

**Comment by k0np4ku** [comment]
I've decrypted the scripts, but it seems it's just an old scripts from a month or two month ago.

**Comment by lkq13905940077** [comment]
How did you do that? Why can't I open it? What if I want to encrypt this way?

**Comment by k0np4ku** [comment]
Is there some particular reason that you want to open this scripts? Well, trying to look into the inside and getting the same functions will be possible.

**Comment by lkq13905940077** [comment]
I have a black card bought by Taobao. If you are willing to register a QQ, you can bind it with that card, and facilitate our more effective communication.

**Comment by lkq13905940077** [comment]
I'm very sorry, but can you tell me more about it? Whenever I use debug, I crash.

**Comment by lkq13905940077** [comment]
Do you mean let me use CMD to compile dump directly?

**Comment by lkq13905940077** [comment]
![cache_7af8c0298bcace2c](https://user-images.githubusercontent.com/42605726/44958278-8d507d00-af10-11e8-834c-8dced4ccec88.jpg)
Also can’t

**Comment by k0np4ku** [comment]
Use Unity AssetBundle Extractor, not LuaHelper.

**Comment by lkq13905940077** [comment]
How to use it？I haven't used this software.
