### ISSUE TITLE
stuck at loading  JP version 1.3.62.

### ISSUE THREAD

**Issue by nanika0000** [k0np4ku/Azur-Lane-Scripts-Autopatcher#4]
![screenshot_2018-07-12-21-34-52](https://user-images.githubusercontent.com/40513366/42633495-a7b31342-861b-11e8-846f-a01d4e6a3b42.png)
i used Azur Lane Scripts Autopatcher v2.7

**Comment by k0np4ku** [comment]
Do you get exception detected and generated logs.txt?

**Comment by k0np4ku** [comment]
@nanika0000  @uvdpqfa If the problem is still occurs to you, try download the latest version (v2.7.1) and turn DebugMode to true (by editing Azurlane.ini).

The program will generate debug.zip after it finished doing its job, afterwards please upload the said file here so that I can see what's the problem.

**Comment by uvdpqfa** [comment]
[debug.zip](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2191717/debug.zip)
[Logs.txt](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2191718/Logs.txt)

**Comment by ParanoidDoll** [comment]
I've got a similar case here. Exception detected and generated logs, tried running the game with the generated script and it got stuck at loading.

here is my debug.zip file.
[debug.zip](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2191933/debug.zip)

**Comment by nanika0000** [comment]
[Logs.txt](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2192226/Logs.txt)
[debug.zip](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2192227/debug.zip)
i try v2.7.1. but stuck at loading

**Comment by k0np4ku** [comment]
As a quick solution, I've uploaded all generated scripts, check it here: https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/tree/generated

**Comment by nanika0000** [comment]
I tried that, I was able to log in.
