### ISSUE TITLE
In the first place the file is no longer output

### ISSUE THREAD

**Issue by nanika0000** [k0np4ku/Azur-Lane-Scripts-Autopatcher#6]
Today, jp ver up.
i try Azur-Lane-Scripts-Autopatcher
but It does not even generate a remodeled file
[debug.zip](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2194930/debug.zip)
[Logs.txt](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2194931/Logs.txt)

**Comment by k0np4ku** [comment]
set DebugMode to false.

**Comment by nanika0000** [comment]
like JP version 1.3.62,stuck at loading

**Comment by k0np4ku** [comment]
Does the tool was working fine before version 1.3.62?

Guess you need to wait until I rewrite the whole program and just get the scripts from the link I provided yesterday in the meantime.

**Comment by tmpnuki** [comment]
hi, @k0np4ku 
KR 1.3.10 version has same issue.
[debug.zip](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2204156/debug.zip)
[Logs.txt](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2204157/Logs.txt)

Also, the generate scripts does not working.
I will wait until you rewrite the whole program.

Always thank your tools.
Great Day!

**Comment by k0np4ku** [comment]
@tmpnuki New version is up. If you still has the same issue, generated scripts are there for you.
