### ISSUE TITLE
Azur Lane CN 1.8.9 with 2.7.1

### ISSUE THREAD

**Issue by Sora92** [k0np4ku/Azur-Lane-Scripts-Autopatcher#7]
[debug.zip](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2195139/debug.zip)
[Logs.txt](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2195140/Logs.txt)
I tried every version of the program and got the exception thing every time and now the same with 2.7.1 :(

**Comment by k0np4ku** [comment]
@Sora92 New version is up. If you still has the same issue, generated scripts are there for you.
