### ISSUE TITLE
script update

### ISSUE THREAD

**Issue by uvdpqfa** [k0np4ku/Azur-Lane-Scripts-Autopatcher#8]
Please update to JP version 1.4.2

**Comment by khwjho** [comment]
Korean Version The patch was released late on the night of July 17th. Update the script file. Thx

**Comment by k0np4ku** [comment]
@uvdpqfa @khwjho They're updated.

**Comment by khwjho** [comment]
I always thank you.

2018년 7월 18일 (수) 오후 11:13, k0np4ku <notifications@github.com>님이 작성:

**Comment by khwjho** [comment]
26 days Kr. Cn. Jp. There will be a version update. I am waiting for the
script file update.

2018년 7월 18일 (수) 오후 11:16, 김지운 <kjwjho0902@gmail.com>님이 작성:

**Comment by khwjho** [comment]
The kr version has been updated. Please replace the script file.

**Comment by khwjho** [comment]
Can I add weak enemy mode?

**Comment by k0np4ku** [comment]
Look here my buddy, I don't publish the autopatcher on github for no reason. You can be an independent and do it yourself, otherwise, you can be a dependent who always depending on other people.
